create table time(
    id number generated by default as identity,
    nome varchar(100),
    vitorias number default 0,
    empates number default 0,
    derrotas number default 0,
    gols_pro number default 0,
    gols_contra number default 0,
    primary key(id)
);

create table partida(
    id number generated by default as identity,
    mandante_id number,
    gols_mandante number,
    visitante_id number,
    gols_visitante number,
    primary key(id),
    foreign key(mandante_id) references time(id),
    foreign key(visitante_id) references time(id)
);