CREATE TABLE T_TESTE ( ID_TESTE INTEGER, NM_TESTE VARCHAR2(50) );
ALTER TABLE T_TESTE ADD DT_NACIMTO DATE;
ALTER TABLE T_TESTE DROP COLUMN DT_NACIMTO;
ALTER TABLE T_TESTE ADD DT_NASCIMENTO DATE;
ALTER TABLE T_TESTE MODIFY NM_TESTE VARCHAR2(50) NOT NULL;

ALTER TABLE T_TESTE ADD CONSTRAINT PK_TESTE PRIMARY KEY ( ID_TESTE);
ALTER TABLE T_TESTE ADD CONSTRAINT UN_TESTE_NOME UNIQUE (NM_TESTE);

describe t_teste
alter table t_teste add st_teste varchar2(1);
alter table t_teste add constraint ck_teste_status check (st_teste in ('A','I'));

truncate table t_teste;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
where table_name = 'T_TESTE';