INSERT INTO T_RHSTU_PACIENTE
(ID_PACIENTE,NM_PACIENTE,NR_CPF,NM_RG,DT_NASCIMENTO,FL_SEXO_BIOLOGICO,DS_ESCOLARIDADE,DS_ESTADO_CIVIL,NM_GRUPO_SANGUINEO,NR_ALTURA,NR_PESO )
VALUES
(1, 'Maria Silva', 123456789, '12345678', '14-AUG-25', 'M', 'Superior', 'Solteira', 'B+', 1.60, 70);

select sysdate from dual;
desc T_RHSTU_PACIENTE
select * from T_RHSTU_PACIENTE