-- ======================================
-- Aluno 1: Matheus Moya de Oliveira - RM562822
-- Aluno 2: Daniel Nicolas Leoterio   - RM562186
-- ======================================

DROP TABLE T_SLV_AUTOR_LIVRO CASCADE CONSTRAINTS;
DROP TABLE T_SLV_LIVRO CASCADE CONSTRAINTS;
DROP TABLE T_SLV_AUTOR CASCADE CONSTRAINTS;
DROP TABLE T_SLV_CATEGORIA CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_SLV_CATEGORIA;
DROP SEQUENCE SEQ_SLV_LIVRO;
DROP SEQUENCE SEQ_SLV_AUTOR;