-- CRIAÇÃO DA TABELA T_SLV_CATEGORIA

CREATE TABLE T_SLV_CATEGORIA (
    CD_CATEGORIA        NUMBER(3),
    DS_SIGLA_CATEGORIA  CHAR(3),
    DS_CATEGORIA        VARCHAR2(30)
);

-- CRIAÇÃO DA TABELA T_SLV_LIVRO

CREATE TABLE T_SLV_LIVRO (
    NR_ISBN             NUMBER(8),
    CD_CATEGORIA        NUMBER(3),
    NM_TITULO           VARCHAR2(50),
    DS_SINOPSE          VARCHAR2(200),
    NR_EDICAO           NUMBER(2),
    NR_ANO              NUMBER(4)
);

-- CRIAÇÃO DA TABELA T_SLV_AUTOR_LIVRO

CREATE TABLE T_SLV_AUTOR_LIVRO (
    NR_ISBN             NUMBER(8),
    CD_AUTOR            NUMBER(3),
    ST_AUTOR_PRINCIPAL  NUMBER(1)
);

-- CRIAÇÃO DA TABELA T_SLV_AUTOR

CREATE TABLE T_SLV_AUTOR (
    CD_AUTOR            NUMBER(3),
    NM_PRIMEIRO_AUTOR   VARCHAR2(20),
    NM_SEGUNDO_AUTOR    VARCHAR2(40)
);

-- COLOCANDO AS PRIMARY KEYS

ALTER TABLE T_SLV_AUTOR ADD CONSTRAINT PK_AUTOR PRIMARY KEY (CD_AUTOR);
ALTER TABLE T_SLV_CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CD_CATEGORIA);
ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT PK_LIVRO PRIMARY KEY (NR_ISBN);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT PK_AUTOR_LIVRO PRIMARY KEY (NR_ISBN, CD_AUTOR);

-- COLOCANDO AS FOREIGN KEY

ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT FK_LIVRO_CATEGORIA FOREIGN KEY (CD_CATEGORIA) REFERENCES T_SLV_CATEGORIA (CD_CATEGORIA);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO_AUTOR FOREIGN KEY (CD_AUTOR) REFERENCES T_SLV_AUTOR (CD_AUTOR);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO_LIVRO FOREIGN KEY (NR_ISBN) REFERENCES T_SLV_LIVRO (NR_ISBN);

-- COLOCANDO AS UNIQUES

ALTER TABLE T_SLV_CATEGORIA ADD CONSTRAINT UN_LIVRO_CATEGORIA UNIQUE (DS_SIGLA_CATEGORIA);
ALTER TABLE T_SLV_CATEGORIA ADD CONSTRAINT UN_SLV_CATEGORIA_DESC UNIQUE (DS_CATEGORIA);

-- ALTERANDO ATRIBUTOS DA TABELA T_SLV_CATEGORIA

ALTER TABLE T_SLV_CATEGORIA MODIFY (CD_CATEGORIA CONSTRAINT CK_CD_CATEGORIA NOT NULL);
ALTER TABLE T_SLV_CATEGORIA MODIFY (DS_SIGLA_CATEGORIA CONSTRAINT CK_DS_SIGLA_CATEGORIA NOT NULL);
ALTER TABLE T_SLV_CATEGORIA MODIFY (DS_CATEGORIA CONSTRAINT CK_DS_CATEGORIA NOT NULL);

-- ALTERANDO ATRIBUTOS DA TABLEA T_SLV_LIVRO

ALTER TABLE T_SLV_LIVRO MODIFY (NR_ISBN CONSTRAINT CK_NR_ISBN NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (NM_TITULO CONSTRAINT CK_NM_TITULO NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (DS_SINOPSE CONSTRAINT CK_DS_SINOPSE NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (NR_EDICAO CONSTRAINT CK_NR_EDICAO NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (NR_ANO CONSTRAINT CK_NR_ANO NOT NULL);

-- ALTERANDO ATRIBUTOS DA TABELA T_SLV_AUTOR_LIVRO

ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY (ST_AUTOR_PRINCIPAL CONSTRAINT CK_ST_AUTOR_PRINCIPAL NOT NULL);

-- ALTERANDO ATRIBUTOS DA TABELA T_SLV_AUTOR

ALTER TABLE T_SLV_AUTOR MODIFY (NM_PRIMEIRO_AUTOR CONSTRAINT CK_NM_PRIMEIRO_AUTOR NOT NULL);
ALTER TABLE T_SLV_AUTOR MODIFY (NM_SEGUNDO_AUTOR CONSTRAINT CK_NM_SEGUNDO_AUTOR NOT NULL);




