-- CRIAÇÃO DA TABELA T_SLV_CATEGORIA

CREATE TABLE T_SLV_CATEGORIA (
    CD_CATEGORIA        NUMBER(3),
    DS_SIGLA_CATEGORIA  CHAR(3),
    DS_CATEGORIA        VARCHAR2(30)
);

-- CRIAÇÃO DA TABELA T_SLV_LIVRO

CREATE TABLE T_SLV_LIVRO (
    NR_ISBN             NUMBER(8),
    CD_CATEGORIA        NUMBER(3),
    NM_TITULO           VARCHAR2(50),
    DS_SINOPSE          VARCHAR2(200),
    NR_EDICAO           NUMBER(2),
    NR_ANO              NUMBER(4)
);

-- CRIAÇÃO DA TABELA T_SLV_AUTOR_LIVRO

CREATE TABLE T_SLV_AUTOR_LIVRO (
    NR_ISBN             NUMBER(8),
    CD_AUTOR            NUMBER(3),
    ST_AUTOR_PRINCIPAL  NUMBER(1)
);

-- CRIAÇÃO DA TABELA T_SLV_AUTOR

CREATE TABLE T_SLV_AUTOR (
    CD_AUTOR            NUMBER(3),
    NM_PRIMEIRO_AUTOR   VARCHAR2(20),
    NM_SEGUNDO_AUTOR    VARCHAR2(40)
);

-- COLOCANDO AS PRIMARY KEYS

ALTER TABLE T_SLV_AUTOR ADD CONSTRAINT PK_AUTOR PRIMARY KEY (CD_AUTOR);
ALTER TABLE T_SLV_CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (CD_CATEGORIA);
ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT PK_LIVRO PRIMARY KEY (NR_ISBN);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT PK_AUTOR_LIVRO PRIMARY KEY (NR_ISBN, CD_AUTOR);

-- COLOCANDO AS FOREIGN KEY

ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT FK_LIVRO_CATEGORIA FOREIGN KEY (CD_CATEGORIA) REFERENCES T_SLV_CATEGORIA (CD_CATEGORIA);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO_AUTOR FOREIGN KEY (CD_AUTOR) REFERENCES T_SLV_AUTOR (CD_AUTOR);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO_LIVRO FOREIGN KEY (NR_ISBN) REFERENCES T_SLV_LIVRO (NR_ISBN);

-- COLOCANDO AS UNIQUES

ALTER TABLE T_SLV_CATEGORIA ADD CONSTRAINT UN_SLV_CATEGORIA_SIGLA UNIQUE (DS_SIGLA_CATEGORIA);
ALTER TABLE T_SLV_CATEGORIA ADD CONSTRAINT UN_SLV_CATEGORIA_DESC UNIQUE (DS_CATEGORIA);

-- ALTERANDO ATRIBUTOS DA TABELA T_SLV_CATEGORIA

ALTER TABLE T_SLV_CATEGORIA MODIFY (CD_CATEGORIA CONSTRAINT CK_CD_CATEGORIA NOT NULL);
ALTER TABLE T_SLV_CATEGORIA MODIFY (DS_SIGLA_CATEGORIA CONSTRAINT CK_DS_SIGLA_CATEGORIA NOT NULL);
ALTER TABLE T_SLV_CATEGORIA MODIFY (DS_CATEGORIA CONSTRAINT CK_DS_CATEGORIA NOT NULL);

-- ALTERANDO ATRIBUTOS DA TABLEA T_SLV_LIVRO

ALTER TABLE T_SLV_LIVRO MODIFY (NR_ISBN CONSTRAINT CK_NR_ISBN NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (NM_TITULO CONSTRAINT CK_NM_TITULO NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (DS_SINOPSE CONSTRAINT CK_DS_SINOPSE NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (NR_EDICAO CONSTRAINT CK_NR_EDICAO NOT NULL);
ALTER TABLE T_SLV_LIVRO MODIFY (NR_ANO CONSTRAINT CK_NR_ANO NOT NULL);

-- ALTERANDO ATRIBUTOS DA TABELA T_SLV_AUTOR_LIVRO

ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY (ST_AUTOR_PRINCIPAL CONSTRAINT CK_ST_AUTOR_PRINCIPAL NOT NULL);

-- ALTERANDO ATRIBUTOS DA TABELA T_SLV_AUTOR

ALTER TABLE T_SLV_AUTOR MODIFY (NM_PRIMEIRO_AUTOR CONSTRAINT CK_NM_PRIMEIRO_AUTOR NOT NULL);
ALTER TABLE T_SLV_AUTOR MODIFY (NM_SEGUNDO_AUTOR CONSTRAINT CK_NM_SEGUNDO_AUTOR NOT NULL);

-- ADICIONANDO OS CHECKS

ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT CK_SLV_LIVRO_ANO CHECK (NR_ANO > 0);
ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT CK_SLV_LIVRO_EDICAO CHECK (NR_EDICAO > 0);

ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT CK_SLV_AUTOR_LIVRO_STATUS CHECK (ST_AUTOR_PRINCIPAL IN (1, 2));

-- 3.1

ALTER TABLE T_SLV_CATEGORIA RENAME COLUMN DS_SIGLA_CATEGORIA TO DS_SIGLA_CATEG;

--  3.2

ALTER TABLE T_SLV_CATEGORIA RENAME CONSTRAINT UN_SLV_CATEGORIA_DESC TO UK_SLV_CATEGORIA_DS_CATEG;

-- 3.3 

ALTER TABLE T_SLV_AUTOR MODIFY (NM_SEGUNDO_AUTOR VARCHAR2(90));

-- 3.4

ALTER TABLE T_SLV_AUTOR ADD (DS_EMAIL VARCHAR2(40));
ALTER TABLE T_SLV_AUTOR MODIFY (DS_EMAIL CONSTRAINT NN_SLV_AUTOR_EMAIL NOT NULL);

-- 3.5

ALTER TABLE T_SLV_AUTOR MODIFY (DS_EMAIL VARCHAR2(60) NULL);

-- 3.6

ALTER TABLE T_SLV_AUTOR_LIVRO MODIFY (NR_ISBN NUMBER(13));

-- 3.7

ALTER TABLE T_SLV_AUTOR_LIVRO DROP CONSTRAINT FK_AUTOR_LIVRO_LIVRO;
ALTER TABLE T_SLV_LIVRO DROP CONSTRAINT PK_LIVRO;
ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT PK_SLV_AUTOR_LIVRO PRIMARY KEY (NR_ISBN);
ALTER TABLE T_SLV_AUTOR_LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO_LIVRO FOREIGN KEY (NR_ISBN) REFERENCES T_SLV_LIVRO (NR_ISBN);

-- 3.8

ALTER TABLE T_SLV_AUTOR ADD (NM_PAIS_ORIGEM VARCHAR2(30));

-- 3.9

ALTER TABLE T_SLV_LIVRO ADD CONSTRAINT UN_SLV_LIVRO_TITULO UNIQUE (NM_TITULO);
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'T_SLV_LIVRO';

-- 3.10

ALTER TABLE T_SLV_AUTOR_LIVRO DROP CONSTRAINT FK_AUTOR_LIVRO_AUTOR;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'T_SLV_AUTOR_LIVRO';

-- 3.11

ALTER TABLE T_SLV_LIVRO DROP CONSTRAINT PK_SLV_LIVRO CASCADE;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'T_SLV_LIVRO';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'T_SLV_LIVRO';
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'T_SLV_AUTOR_LIVRO';













