DROP TABLE T_RHSTU_BAIRRO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_CIDADE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_CONSULTA CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_CONSULTA_FORMA_PAGTO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_CONTATO_PACIENTE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_EMAIL_PACIENTE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_ENDERECO_PACIENTE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_ESTADO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_FORMA_PAGAMENTO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_LOGRADOURO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_MEDICAMENTO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_MEDICO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_PACIENTE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_PACIENTE_PLANO_SAUDE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_PLANO_SAUDE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_PRESCICAO_MEDICA CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_TELEFONE_PACIENTE CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_TIPO_CONTATO CASCADE CONSTRAINTS 
;

DROP TABLE T_RHSTU_UNID_HOSPITALAR CASCADE CONSTRAINTS 
;