CREATE TABLE T_PRODUTO (
        CD_PRODUTO NUMBER,
        NM_PRODUTO VARCHAR2(50),
        DS_PRODUTO VARCHAR2(255),
        VL_PRODUTO NUMBER
);

ALTER TABLE T_PRODUTO ADD CONSTRAINT PK_CD_PRODUTO PRIMARY KEY (CD_PRODUTO);

ALTER TABLE T_PRODUTO MODIFY (CD_PRODUTO NUMBER(6));
ALTER TABLE T_PRODUTO MODIFY (VL_PRODUTO NUMBER(10,2));

DESC T_PRODUTO;