INSERT INTO pessoa(nome, cidade, cep) VALUES ('Kevin Abreu', 'da Mata do Galho', '63198-170');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maitê Cassiano', 'Rios', '79174-044');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luiz Gustavo Cunha', 'Melo de da Cruz', '86430735');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Larissa Jesus', 'Novaes das Flores', '57675-663');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Heitor Cassiano', 'Novaes', '86279511');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Samuel Macedo', 'Costa de Minas', '66212-350');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Heitor Oliveira', 'Casa Grande da Prata', '47956574');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Catarina Siqueira', 'Viana', '28010933');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Arthur Miguel Aparecida', 'Vasconcelos', '92570-949');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Pedro Henrique Alves', 'Novaes', '63696-524');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ester Borges', 'Pacheco de Carvalho', '32272113');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Thales Pereira', 'Vargas', '95485-148');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luigi Cirino', 'Rezende', '16936-266');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Maria Luiza Nogueira', 'Rodrigues', '24675-493');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Liam Rodrigues', 'Moreira Verde', '90309599');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Milena Nascimento', 'da Rosa', '41539725');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Alice Rodrigues', 'Andrade', '90576805');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Gabriel da Rocha', 'Casa Grande', '27675817');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Olívia das Neves', 'Moraes', '03797550');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Maria Alice da Costa', 'da Cunha', '15867799');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Thales Moraes', 'Gonçalves', '23321-082');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Valentim Correia', 'Moraes', '20172-378');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('João Pedro Leão', 'Vargas', '73407-150');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Breno Sá', 'Siqueira de Porto', '35702428');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Brenda Cavalcante', 'Jesus de da Cruz', '30253-640');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Kevin da Cruz', 'Jesus', '38481807');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Apollo Aragão', 'Santos', '06290644');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Nicole Sá', 'da Cunha', '10159781');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Daniela Mendonça', 'Borges da Praia', '02168798');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Stephany da Rosa', 'Macedo', '28839650');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Natália Dias', 'Vieira', '37356-200');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Gabrielly da Rosa', 'Barbosa', '07158809');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Vitor Gabriel Rodrigues', 'Martins da Mata', '64371901');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Vicente Freitas', 'Jesus', '92760-596');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Helena Vargas', 'Peixoto da Serra', '02075879');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Heitor da Rocha', 'Rocha', '64228811');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Eduarda Lima', 'Campos da Mata', '96899-184');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Helena Silva', 'Câmara de Albuquerque', '46994-128');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Gabriel das Neves', 'Souza da Praia', '00714-685');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('João Albuquerque', 'Pacheco', '96069-111');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bernardo Duarte', 'Garcia do Sul', '98295-726');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Pedro Lucas Pastor', 'Martins da Prata', '05141-542');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Alícia Fernandes', 'Lima', '90929278');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Nicole da Rosa', 'Albuquerque Grande', '05695611');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Isadora Sá', 'Albuquerque', '37006452');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Hellena Moreira', 'Carvalho de Correia', '06890247');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Thomas Freitas', 'Marques da Mata', '90725211');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Alícia Sales', 'Sá do Campo', '97729-209');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Vitor Rodrigues', 'Vasconcelos de Alves', '58046851');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Rafaela Carvalho', 'Martins de Carvalho', '49635890');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Rafaela Casa Grande', 'da Luz', '49929-076');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Eduardo da Rocha', 'Abreu', '86729-787');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Anthony Gabriel Araújo', 'Moreira', '92016892');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ravi Lucca da Cruz', 'Castro', '20843499');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Levi Cirino', 'Sampaio', '02936-273');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Vitória Marques', 'Castro de Leão', '70473021');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Caroline Pacheco', 'Cunha', '54186465');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Erick Araújo', 'Lopes', '52849994');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dra. Cecília Leão', 'Nascimento do Oeste', '75815633');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luana Ribeiro', 'Porto do Campo', '43861037');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luana Caldeira', 'Cavalcanti', '05707193');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Marcela Cavalcante', 'Barros de Silva', '63751-815');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maitê Vargas', 'Rodrigues da Praia', '30731243');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Otávio Cavalcanti', 'Ribeiro', '55242901');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Kaique Monteiro', 'Guerra do Oeste', '11517508');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Yasmin Andrade', 'Teixeira Alegre', '20426-449');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('João Guilherme Santos', 'Rodrigues da Serra', '66596978');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Manuela da Cruz', 'Camargo de Vieira', '73675223');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ian Costela', 'Dias', '91076478');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Aurora Oliveira', 'Vargas de Silveira', '33614-488');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Davi Caldeira', 'Barros', '73155014');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dante da Cruz', 'da Paz do Galho', '66868597');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Cecília Pimenta', 'Santos da Prata', '03848287');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Milena Barbosa', 'Ribeiro', '45202-752');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Lorenzo Pinto', 'Caldeira Verde', '97327-861');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Paulo Andrade', 'Barros', '54146518');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ana Clara Barros', 'Novaes', '95627-482');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sofia Sampaio', 'Barros', '52940-074');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Júlia Gonçalves', 'Cassiano do Galho', '35752-665');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('João Vitor Ferreira', 'Alves', '67503844');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luiz Fernando Garcia', 'Souza Grande', '84539-135');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Caio Gonçalves', 'Fonseca dos Dourados', '34618-671');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dra. Ana Lívia da Cruz', 'Rocha', '15488821');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ana Lívia das Neves', 'Farias', '33898-165');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dra. Helena Sá', 'Vieira da Prata', '29157-563');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Lucca da Rosa', 'Carvalho da Serra', '42686921');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luara Pacheco', 'Rodrigues', '43918801');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Matheus Azevedo', 'Casa Grande do Oeste', '18649-898');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Davi Miguel Lima', 'Santos de Minas', '09718743');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Matheus Abreu', 'Correia dos Dourados', '71853-793');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dra. Brenda Sousa', 'Araújo', '29398270');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Hadassa Sousa', 'Alves', '04602-483');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Flor Borges', 'da Mata', '12506-205');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Theo Costela', 'da Luz', '42472372');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sofia da Costa', 'Andrade', '69308-243');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Vinícius Campos', 'Sá', '86273823');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ravi Borges', 'Macedo', '24483171');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bella Farias', 'Aragão', '47339683');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Lucca Almeida', 'Câmara', '13666-426');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Arthur Gabriel Guerra', 'da Conceição', '11975-179');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Sophia Andrade', 'Albuquerque de Moraes', '36964148');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Lara Moraes', 'da Rosa', '11406839');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Raul Novaes', 'Novais de Souza', '76835845');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Daniel Guerra', 'Duarte', '61630-402');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Isadora Costela', 'Costa', '65147729');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Alice Lima', 'Moreira', '80759865');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Nicolas Machado', 'Silveira Paulista', '03778-316');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Hadassa Brito', 'Nascimento das Flores', '30234-877');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Helena Moura', 'Ribeiro', '63408910');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Rafael Souza', 'Jesus de Monteiro', '33395005');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Gael Henrique Câmara', 'Abreu de Montenegro', '94665890');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Júlia Campos', 'Sousa das Flores', '37538824');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Milena Sampaio', 'Pinto Grande', '84884-077');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Lucca Sampaio', 'Barros', '18973-433');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sra. Aylla Pinto', 'Cunha do Norte', '17301259');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Eduardo Abreu', 'Pastor', '94226-336');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ravi Lucca Souza', 'Porto', '79069135');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ayla Ramos', 'Nogueira do Amparo', '60182459');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Isabella Machado', 'Rocha', '98907-654');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Breno Lopes', 'da Mota', '64491-492');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Apollo Vargas', 'Fernandes de Barros', '82901339');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maya Costa', 'Duarte da Serra', '62536073');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Alexandre Sá', 'Ramos', '24282037');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Agatha da Paz', 'Duarte do Campo', '71012-156');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Paulo Fonseca', 'Costela de Pereira', '34893-801');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Andrade', 'Montenegro do Sul', '74687879');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Davi Miguel Cavalcanti', 'Correia', '49869-773');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Sophia Nascimento', 'Pimenta Grande', '55018126');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Rafaela Vieira', 'Marques Grande', '93168-096');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Antônio Campos', 'Silva', '64317-345');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Rael Sousa', 'Ribeiro da Serra', '04356564');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Maria Clara Freitas', 'Campos do Campo', '63896-549');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dra. Ester da Luz', 'Teixeira', '06876-692');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luiz Henrique Macedo', 'Vieira das Pedras', '84988-890');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Davi Miguel Costa', 'Duarte', '36582581');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Davi Lucca Rezende', 'Viana de da Costa', '78107550');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luiz Miguel Dias', 'Aragão do Norte', '56691981');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('João Gabriel Cardoso', 'das Neves de Camargo', '68796330');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Paulo Cavalcante', 'Cavalcanti Verde', '14129834');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Benicio Garcia', 'Santos', '34170-062');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dra. Maria Júlia Rocha', 'Rios', '07047344');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Théo Borges', 'Costa', '97649283');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bianca Andrade', 'Borges Grande', '90047311');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Daniel Cavalcante', 'das Neves', '39034648');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Eduarda da Costa', 'Albuquerque da Mata', '84110928');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Yan Ribeiro', 'Fonseca do Sul', '36110351');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Josué Pires', 'Viana do Amparo', '56380-957');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bárbara Sá', 'Carvalho', '92442302');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Kevin da Paz', 'Novaes de Goiás', '87556-207');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Antony Aparecida', 'Borges de Pimenta', '56645683');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luara Carvalho', 'Macedo', '99388865');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Lara Novais', 'Fogaça das Pedras', '07477-064');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Alícia Rocha', 'Cirino da Mata', '60138-242');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sra. Allana Brito', 'Alves de Minas', '85520-630');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bento da Conceição', 'Pimenta de Ramos', '90236-186');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Ana Carolina Correia', 'Cavalcanti de Novaes', '09490-725');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Milena Farias', 'da Luz', '32120-987');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luara Correia', 'Novaes', '07300722');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Laís Martins', 'da Paz da Serra', '56186587');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Antônio Câmara', 'Almeida', '05233-823');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luara Lima', 'Santos', '30405289');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Enzo Melo', 'Aparecida do Galho', '43576-395');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Benjamin Sampaio', 'Araújo Paulista', '16542-809');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. José Pedro Cavalcanti', 'Caldeira do Amparo', '55700158');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Leandro das Neves', 'Sampaio da Prata', '73696-890');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Noah Machado', 'Leão', '65783-932');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Melissa Campos', 'Cirino de Sá', '93577-002');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Raul Macedo', 'Siqueira', '95845-482');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Emanuelly Carvalho', 'Caldeira', '63414-521');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bruna Oliveira', 'Pires', '19822923');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Lavínia Vieira', 'Ferreira do Sul', '54784095');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Zoe Lima', 'Castro do Amparo', '09291279');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Eloá da Rocha', 'Barbosa', '27657-163');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Henrique Carvalho', 'Freitas dos Dourados', '13258854');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dante Cardoso', 'Jesus da Prata', '63748660');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Anthony Martins', 'Montenegro do Oeste', '23959540');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Marcos Vinicius Novais', 'Pires de Vargas', '22018767');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Raquel Pacheco', 'Mendonça', '44675589');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Fernanda Gomes', 'da Conceição das Flores', '90866077');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Mathias Rodrigues', 'Alves do Amparo', '68919-729');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Alexia Teixeira', 'Câmara de Rios', '45656-504');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Melissa Camargo', 'Sousa de da Rosa', '18312-056');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Júlia da Cunha', 'Vasconcelos Verde', '08270-560');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Bento Pacheco', 'da Rosa', '91503508');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sara Rios', 'Andrade das Flores', '63822660');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Brayan Sá', 'Mendes', '88309-126');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Kaique Cavalcante', 'Pacheco', '42301581');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sr. Thales da Rocha', 'Aragão de Martins', '47461-325');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Benjamin Lima', 'da Costa', '79483-476');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Srta. Alícia Barbosa', 'Marques da Mata', '18052661');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Pedro Lucas Borges', 'Caldeira de Cavalcante', '26165-574');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Eloah Cavalcanti', 'Abreu', '05510-249');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('João Felipe Farias', 'da Paz do Galho', '75605-977');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Eduardo Sá', 'Andrade', '38454015');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Pedro Lucas da Conceição', 'Vieira', '47218-069');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Luiz Fernando Marques', 'Jesus de Ferreira', '05027068');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Isadora da Conceição', 'Lima', '65281-399');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Dr. Pietro Monteiro', 'Abreu Paulista', '89085-167');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Heitor Sousa', 'Viana do Norte', '31504662');
INSERT INTO pessoa(nome, cidade, cep) VALUES ('Sofia Campos', 'Gonçalves', '68873-735');
