create table cliente (
    id number generated by default as identity,
    nome varchar2(100) not null,
    documento varchar2(30),
    telefone varchar2(20),
    constraint pk_cliente primary key (id)
);

create table endereco (
    id number generated by default as identity,
    pessoa_id number not null,
    cep varchar2(15),
    logradouro varchar2(100),
    numero varchar2(15),
    bairro varchar2(30),
    cidade varchar2(30),
    complemento varchar2(15),
    uf varchar2(2),
    constraint pk_endereco primary key (id),
    constraint fk_endereco_cliente foreign key (pessoa_id) references cliente(id)
);

create table conta (
    id number generated by default as identity,
    tipo varchar2(20),
    numero varchar2(10),
    senha varchar2(100),
    saldo number(10, 2),
    cliente_id number not null,
    constraint pk_conta primary key (id),
    constraint fk_conta_cliente foreign key (cliente_id) references cliente(id)
);

create table transacao (
    id number generated by default as identity,
    valor number(10, 2) not null,
    data_hora timestamp default current_timestamp,
    destino varchar2(100),
    contraparte varchar2(100),
    tipo varchar2(50),
    conta_id number not null,
    constraint pk_transacao primary key (id),
    constraint fk_transacao_conta foreign key (conta_id) references conta(id)
);

create sequence sq_numero start with 1000 increment by 1;
