create table cliente(
    id number generated by default as identity,
    nome varchar2(100),
    documento varchar2(30),
    telefone varchar2(20),
    primary key(id));

create table endereco(
    pessoa_id number,
    cep varchar2(15),
    logradouro varchar2(100),
    numero varchar2(15),
    bairro varchar2(30),
    cidade varchar2(30),
    complemento varchar2(15),
    uf varchar2(2),
    foreign key(pessoa_id) references cliente(id)
);

create table conta(
    id number generated by default as identity,
    tipo varchar2(20),
    numero varchar2(10),
    senha varchar2(100),
    saldo number(10, 2),
    cliente_id number,
    primary key(id),
    foreign key(cliente_id) references cliente(id)
);

create table transacao(
    id number generated by default as identity,
    valor number(10, 2),
    data_hora timestamp,
    contraparte varchar2(100),
    tipo varchar2(50),
    conta_id number,
    primary key(id),
    foreign key(conta_id) references conta(id)
);

create sequence sq_numero start with 1000;