CREATE TABLE empresa(
    id number generated by default as identity,
    nome varchar(100) not null,
    url varchar(50),
    documento varchar(50),
    telefone varchar(50),
    primary key(id)
);
 
CREATE TABLE carro(
    id number generated by default as identity,
    montadora varchar(50) not null,
    modelo varchar(50) not null,
    ano number,
    placa varchar(20),
    proprietario_id number,
    primary key(id),
    foreign key(proprietario_id) references empresa(id)
);

select * from empresa;
select * from carro;